// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomerCompany = "customer_companies"

// CustomerCompany mapped from table <customer_companies>
type CustomerCompany struct {
	CompanyID   int64   `gorm:"column:company_id;primaryKey" json:"company_id"`
	CompanyName *string `gorm:"column:company_name" json:"company_name"`
}

// TableName CustomerCompany's table name
func (*CustomerCompany) TableName() string {
	return TableNameCustomerCompany
}
