// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	UserID      string  `gorm:"column:user_id;primaryKey" json:"user_id"`
	Login       *string `gorm:"column:login" json:"login"`
	Password    *string `gorm:"column:password" json:"password"`
	Name        *string `gorm:"column:name" json:"name"`
	CompanyID   *string `gorm:"column:company_id" json:"company_id"`
	CreditCards *string `gorm:"column:credit_cards" json:"credit_cards"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
