// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDelivery = "deliveries"

// Delivery mapped from table <deliveries>
type Delivery struct {
	ID                string  `gorm:"column:id;primaryKey" json:"id"`
	OrderItemID       *string `gorm:"column:order_item_id" json:"order_item_id"`
	DeliveredQuantity *string `gorm:"column:delivered_quantity" json:"delivered_quantity"`
}

// TableName Delivery's table name
func (*Delivery) TableName() string {
	return TableNameDelivery
}
