// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID         int64      `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt  *time.Time `gorm:"column:created_at" json:"created_at"`
	OrderName  *string    `gorm:"column:order_name" json:"order_name"`
	CustomerID *string    `gorm:"column:customer_id" json:"customer_id"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
